### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by omerien** [chfoo/tppinputassist#2]
I installed Haxe 4.0.0 and tried to compile the extension but it doesn't work
Error messages :
```
$ make
haxe build.hxml
src/tppinputassist/App.hx:720: characters 32-33 : Void should be String
make: *** [Makefile:6: build] Error 1
```

**Comment by chfoo** [comment]
Sorry, I haven't updated the readme. It should work with the latest version of Haxe 4.2.

**Comment by omerien** [comment]
Successfully compiled ! You can now add that it works on macOS (12.4, ARM processor)
