### ISSUE TITLE
TPP Input Assist error:  querySelector failed

### ISSUE THREAD

**Issue by Zadck** [chfoo/tppinputassist#3]
I'm getting the below when clicking the "tpp input assist" text to pull up the settings, unfortunately meaning the script is only displaying that text right now and cannot function (no overlay). Looks like twitch may be doing what they do best and making changes without telling anyone again? Curiously, inspecting the element, it seems like the statement on line 537 should be working?

TPP Input Assist error:

querySelector failed: .chat-input textarea[data-a-target='chat-input']

Line 537:
let element = this.querySelector(".chat-input textarea[data-a-target='chat-input']");

**Comment by chfoo** [comment]
Twitch has been showing a new chat box over the past few months so the script no longer works for most people. The new chat box doesn't use a normal text box anymore so it's no longer a simple fix. I'll try to find a way to make it work again but I'm not sure how long it will take.

**Comment by omerien** [comment]
Same error, good luck for fixing it! (I'm not doing irony)

**Comment by chfoo** [comment]
I think I fixed it now. Let me know if it's still broken.

**Comment by Zadck** [comment]
It works for me now! Thank you as always for your work haha.
